const PDFDocument = require('pdfkit');
const cloudinary   = require('../config/cloudinary');
const { Readable } = require('stream');

// My design: report is uploaded to Cloudinary and a public URL is stored on the case.
// The reporter receives this URL via email and can view/download it from their dashboard.

const generateRescueReport = async (streetCase) => {
  try {
    await streetCase.populate([
      { path: 'reporter',           select: 'name email phone' },
      { path: 'assignedVet',        populate: { path: 'user', select: 'name phone' } },
      { path: 'assignedVolunteer',  populate: { path: 'user', select: 'name phone' } },
    ]);

    const doc    = new PDFDocument({ margin: 50, size: 'A4' });
    const chunks = [];

    doc.on('data', (chunk) => chunks.push(chunk));

    // Header
    doc.fontSize(22).fillColor('#1D9E75').text('PawRescue', { align: 'center' });
    doc.fontSize(12).fillColor('#888').text('Street Animal Rescue Report', { align: 'center' });
    doc.moveDown(0.5);
    doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor('#E1F5EE').stroke();
    doc.moveDown();

    // Case overview
    sectionHeader(doc, 'Case Overview');
    row(doc, 'Case ID',       streetCase._id.toString());
    row(doc, 'Date Reported', formatDate(streetCase.createdAt));
    row(doc, 'Date Rescued',  formatDate(streetCase.rescuedAt));
    row(doc, 'Injury Type',   capitalize(streetCase.injuryType));
    row(doc, 'Severity',      `${streetCase.severityScore}/5`);
    row(doc, 'Status',        capitalize(streetCase.status));
    doc.moveDown();

    // Location
    sectionHeader(doc, 'Location');
    const coords = streetCase.location?.coordinates || [];
    row(doc, 'GPS',      `${coords[1]}, ${coords[0]}`);
    row(doc, 'Address',  streetCase.location?.address || 'Not provided');
    row(doc, 'Landmark', streetCase.landmark || 'Not provided');
    doc.moveDown();

    // Reporter
    sectionHeader(doc, 'Reported By');
    row(doc, 'Name',  streetCase.reporter?.name  || 'Anonymous');
    row(doc, 'Phone', streetCase.reporterPhone);
    row(doc, 'Email', streetCase.reporter?.email || '-');
    doc.moveDown();

    // Responders
    sectionHeader(doc, 'Responders');
    if (streetCase.assignedVolunteer) {
      row(doc, 'Volunteer', streetCase.assignedVolunteer.user?.name || '-');
      row(doc, 'Volunteer Phone', streetCase.assignedVolunteer.user?.phone || '-');
    } else {
      row(doc, 'Volunteer', 'None assigned');
    }
    if (streetCase.assignedVet) {
      row(doc, 'Vet',       streetCase.assignedVet.user?.name || '-');
      row(doc, 'Vet Phone', streetCase.assignedVet.user?.phone || '-');
      row(doc, 'Clinic',    streetCase.assignedVet.clinicName || '-');
    } else {
      row(doc, 'Vet', 'None assigned');
    }
    doc.moveDown();

    // Dispatch timeline
    if (streetCase.dispatchChain?.length) {
      sectionHeader(doc, 'Dispatch Chain');
      streetCase.dispatchChain.forEach((d, i) => {
        doc.fontSize(10).fillColor('#555')
          .text(`${i + 1}. ${capitalize(d.responderType)} — ${capitalize(d.response)} @ ${formatDate(d.respondedAt || d.sentAt)}`);
      });
      doc.moveDown();
    }

    // Status timeline
    if (streetCase.statusTimeline?.length) {
      sectionHeader(doc, 'Status Timeline');
      streetCase.statusTimeline.forEach((t) => {
        doc.fontSize(10).fillColor('#555')
          .text(`[${formatDate(t.updatedAt)}] ${capitalize(t.status)}${t.note ? ' — ' + t.note : ''}`);
      });
      doc.moveDown();
    }

    // First aid steps taken
    if (streetCase.firstAidStepsTaken?.length) {
      sectionHeader(doc, 'First Aid Taken by Reporter');
      streetCase.firstAidStepsTaken.forEach((s) => {
        doc.fontSize(10).fillColor('#555').text(`• ${s}`);
      });
      doc.moveDown();
    }

    // Footer
    doc.moveDown(2);
    doc.fontSize(9).fillColor('#aaa')
      .text(`Generated by PawRescue on ${formatDate(new Date())}`, { align: 'center' });
    doc.text('pawrescue.in — Every life matters.', { align: 'center' });

    doc.end();

    // Wait for PDF to finish building
    await new Promise((resolve) => doc.on('end', resolve));
    const pdfBuffer = Buffer.concat(chunks);

    // Upload to Cloudinary
    const uploaded = await new Promise((resolve, reject) => {
      const stream = cloudinary.uploader.upload_stream(
        { folder: 'pawrescue/reports', public_id: `report_${streetCase._id}`, resource_type: 'raw', format: 'pdf' },
        (err, result) => err ? reject(err) : resolve(result)
      );
      Readable.from(pdfBuffer).pipe(stream);
    });

    return uploaded.secure_url;
  } catch (err) {
    console.error('Report generation failed:', err.message);
    return null;
  }
};

const sectionHeader = (doc, title) => {
  doc.fontSize(13).fillColor('#1D9E75').text(title);
  doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor('#9FE1CB').lineWidth(0.5).stroke();
  doc.moveDown(0.3);
};

const row = (doc, label, value) => {
  doc.fontSize(10)
    .fillColor('#888').text(`${label}: `, { continued: true })
    .fillColor('#222').text(value || '-');
};

const formatDate = (date) =>
  date ? new Date(date).toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' }) : '-';

const capitalize = (str) =>
  str ? str.replace(/-/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase()) : '-';

module.exports = { generateRescueReport };